steps:

- task: UseRubyVersion@0
  inputs:
    versionSpec: '= 2.4'
  condition: not(eq(variables['Agent.OS'], 'Darwin')) # not possible on Mac

- script: |
    ruby bin/rake spec:deps
  displayName: 'ruby bin/rake spec:deps'

- script: |
    ruby bin/rspec ./spec/bundler/source_spec.rb:66
  displayName: 'ruby bin/rspec ./spec/bundler/source_spec.rb:66'

- script: |
    ruby bin/rspec ./spec/bundler/source_spec.rb
  displayName: 'ruby bin/rspec ./spec/bundler/source_spec.rb'

- script: |
    ruby bin/rspec
  displayName: 'ruby bin/rspec'

- task: PublishTestResults@2
  inputs:
    testRunner: JUnit
    testResultsFiles: rspec/bundler-junit-results.xml
  displayName: Publish test results
  condition: succeededOrFailed()